spring:
  application:
    name: claim

  cache:
    type: jcache

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: rg.hibernate.cache.ehcache.EhCacheRegionFactory
        format_sql: true
        show-sql: true

      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
        persistence:
          sharedCache:
            mode: ALL

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:/claim  #메모리기반으로 사용
    username: sa
    password: claim

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.cache: DEBUG
    net.sf.ehcache: DEBUG
