server:
  tomcat:
    uri-encoding: UTF-8

  servlet:
    context-path:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: claim

  cache:
    jcache:
      config: classpath:ehcache.xml

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:/claim  #메모리기반으로 사용
    username: sa
    password: claim

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
